version: '2'
services:
  halopesa-app:
    image: halopesa
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@halopesa-oracle:1521:halopesa
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
